### ISSUE TITLE
Production models?

### ISSUE THREAD

**Issue by andrewrech** [KarchinLab/mhcnuggets#1]
Thank you for providing this wonderful tool. I would like to integrate predictions using `mhcnuggets` into an [R package for ensemble neoepitope prediction](https://github.com/andrewrech/antigen.garnish/issues/13). Could you provide guidance based on your experience for training production models that could be pre-packaged?

I believe this would be helpful to [pVAC-Seq](https://github.com/griffithlab/pVAC-Seq/issues/321) as well.

Thank you!

**Comment by rbhatta8** [comment]
Hi Andrew! That's awesome! By the end of the week we'll be providing the weights for pre-trained production models. Those will be kept updated on this repo as more data flows into the IEDB. Would that suffice for your purposes, or were you thinking of having a pipeline where you'd like to train the models on your end?

**Comment by andrewrech** [comment]
Perfect!

**Comment by rbhatta8** [comment]
Took a bit longer than expected due to some server issues, but production models are now available! Look forward to seeing your ensemble method! :-)
