### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by Stikus** [KarchinLab/mhcnuggets#10]
Hello, current releases of both https://github.com/griffithlab/pVACtools and https://github.com/openvax/mhcflurry doesn't support tensorflow 2.0.0+ and have limitation for tensorflow version: `tensorflow>=1.15.0,<2.0.0`

But using https://github.com/KarchinLab/mhcnuggets as dependency frequently breaks this because here we have https://github.com/KarchinLab/mhcnuggets/blob/master/setup.py#L24 - just tensorflow.

Does mhcnuggets support tensorflow 2.0.0+ or should it be pinned like others?

**Comment by benjaminalbert** [comment]
MHCnuggets works with TensorFlow 2 with some minor fixes. I tested on Debian 10 under WSL-2 (base OS Windows 11) and running Python 3.7.3 with TensorFlow 2.6.1. Here are the steps I needed to take:

```
apt install pkg-config libhdf5-103 libhdf5-dev
pip3 install h5py==2.10.0 --force-reinstall
```
Then change all instances of importing `keras` to `tensorflow.keras`

Lastly, remove the last package in instances of: `tensorflow.keras.layers.core` and `tensorflow.keras.layers.recurrent`, so it should just be `tensorflow.keras.layers`
