### ISSUE TITLE
Activate Travis CI

### ISSUE THREAD

**Issue by richelbilderbeek** [KarchinLab/mhcnuggets#19]
Hi @XiaoshanShao,

On the `richel` branch I've added the first start of adding continuous integration. To be able to show this to you for review, however, I need to activate the repository on Travis CI.

When I go to [https://travis-ci.org/github/KarchinLab/mhcnuggets](https://travis-ci.org/github/KarchinLab/mhcnuggets) I see the following:

![Screenshot from 2020-06-17 09-43-40](https://user-images.githubusercontent.com/2098230/84870508-b1e2fe00-b07f-11ea-95d0-52ad8c7d17ee.png)

In words, it states:

> You don't have sufficient rights to enable this repo on Travis.
> Please contact the admin to enable it or to receive admin rights yourself. 

Do you have the rights to activate the repo? If yes, could you do so?

Thanks, Richel

**Comment by RachelKarchin** [comment]
I have admin rights.

Currently for mhcnuggets  "There is no build on the default branch yet"
 so I can't enable Travis CI
@XiaoshanShao <https://github.com/XiaoshanShao>

We currently have Travis CI turned on for 2020plus, CHASMplus,
probabilistic2020.

@Collin Tokheim <collintokheim@gmail.com>  Did you do that?

**Comment by ctokheim** [comment]
Yep, I turned Travis CI on for my repos. I just toggled "on switch" for the KarchinLab/mhcnuggets repo on the Travis CI website.

**Comment by RachelKarchin** [comment]
Thanks!  I figured it out and believe it is fixed now
@richel@richelbilderbeek.nl <richel@richelbilderbeek.nl>
Let me know if it is working for you.

**Comment by richelbilderbeek** [comment]
Works! Thanks @RachelKarchin!

![Screenshot from 2020-06-18 09-00-34](https://user-images.githubusercontent.com/2098230/84988394-37c77d80-b142-11ea-89a0-e11fb4b04418.png)

**Comment by richelbilderbeek** [comment]
Done :+1:
