### ISSUE TITLE
Bug with some alleles

### ISSUE THREAD

**Issue by jracle85** [KarchinLab/mhcnuggets#24]
Dear MHCnuggets team,

I was playing around with your tool but I got some troubles when predicting different alleles (in general it works, but not for all alleles).

It seems to be an issue with your function searching for the nearest allele when one is absent from the pre-defined ones. Would you be able to fix this issue please?

For example, when running the following command from within python3.8 (using the test data available in your repo):
```
from mhcnuggets.src.predict import predict

predict(class_='II',
        peptides_path='data/test/test_peptides.peps', 
        mhc='HLA-DPA101:03-DPB101:01')

```

We get the following issue:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/Julien/.pyenv/versions/3.8.0/lib/python3.8/site-packages/mhcnuggets/src/predict.py", line 58, in predict
>     predictor_mhc = closest_mhcII(mhc,pickle_path)
>   File "/Users/Julien/.pyenv/versions/3.8.0/lib/python3.8/site-packages/mhcnuggets/src/find_closest_mhcII.py", line 238, in closest_allele
>     closest_mhc = closest_human_allele_supertype(mhc, examples_per_allele)
>   File "/Users/Julien/.pyenv/versions/3.8.0/lib/python3.8/site-packages/mhcnuggets/src/find_closest_mhcII.py", line 134, in closest_human_allele_supertype
>     short_to_full_names)
> NameError: name 'short_to_full_names' is not defined

Thanks! Best regards,

Julien

**Comment by jhuan104** [comment]
Hi Julien,

Thank you for the comment! Make sure that you update mhcnuggets to the most recent version found on pip or github. This was an error contained in an earlier version that is now fixed. Let us know if you have further troubles.

Best,
Justin

**Comment by jracle85** [comment]
Hi Justin,

Thanks for the answer. It seems to work now.

Best,

Julien
