### ISSUE TITLE
Predict import fails after installation using pip 

### ISSUE THREAD

**Issue by christopher-mohr** [KarchinLab/mhcnuggets#29]
After installing MHCnuggets using `pip` (`pip install mhcnuggets`), the import `from mhcnuggets.src.predict import predict` fails.

```
python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:59:23) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mhcnuggets.src.predict import predict
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.7/site-packages/mhcnuggets/src/predict.py", line 15, in <module>
    from keras.optimizers import Adam
ImportError: cannot import name 'Adam' from 'keras.optimizers' (.../lib/python3.7/site-packages/keras/optimizers.py)
``` 

The following versions have been installed:
```
 tensorflow-2.8.0
 keras-2.8.0
```

The correct import statement for the respective `keras` version seems to be the following:
```
from keras.optimizers import adam_v2
```

Are there plans for making MHCnuggets compatible with these versions and to create a new release?

**Comment by benjaminalbert** [comment]
The current version is run under Python 2 and TensorFlow 1, and needs library set up for that compatibility.

To use Python 3 and TensorFlow 2, you can clone the repo and solve the problems discussed here: https://github.com/KarchinLab/mhcnuggets/issues/10#issuecomment-958061371

We are working on a new version of MHCnuggets that uses Python 3 and PyTorch.

**Comment by christopher-mohr** [comment]
> The current version is run under Python 2 and TensorFlow 1, and needs library set up for that compatibility.
> 
> To use Python 3 and TensorFlow 2, you can clone the repo and solve the problems discussed here: [#10 (comment)](https://github.com/KarchinLab/mhcnuggets/issues/10#issuecomment-958061371)
> 
> We are working on a new version of MHCnuggets that uses Python 3 and PyTorch.

Thank you for the update.

Of course you are right, that TensorFlow 2 has different dependencies. However, it does not seem to require too many changes in order to make MHCnuggets compatible with TensorFlow 2, as also pointed out by you in the other issue. It would have been great to have another release of MHCnuggets that includes these changes for people (like us) that would like to use it via (bio)conda since currently it breaks every environment that uses TensorFlow 2.

**Comment by serge2016** [comment]
I would appreciate support of `tensorflow>=2.5.0` also!

**Comment by benjaminalbert** [comment]
@christopher-mohr and @susannasiebert to keep you informed, we just released a new tool called BigMHC, which can be found here: https://github.com/KarchinLab/bigmhc

**Comment by christopher-mohr** [comment]
Hi @benjaminalbert, thanks a lot for the hint! I will have a look at it.
