### ISSUE TITLE
Fewer peptides in output than expected

### ISSUE THREAD

**Issue by leeprichman** [KarchinLab/mhcnuggets#3]
[test_in.txt](https://github.com/KarchinLab/mhcnuggets/files/1242718/test_in.txt)
[test_output.txt](https://github.com/KarchinLab/mhcnuggets/files/1242717/test_output.txt)

I have received the below error message when running mhcnuggets with the provided models for H-2-KB, and in addition, have noticed that I sometimes receive output lists with fewer unique peptides than I put in.  Is there some kind of maximum affinity threshold cutoff for which peptides are not included in the output, and if so, would that explain the error?  Below is the error and command line input that generates this message.  I receive the same error and the same peptides are dropped from the output whether I use -m lstm or -m gru with the appropriate models.

I just want to be sure that if peptides are dropped from the output for not meeting a certain threshold, the output is still indexed correctly such that each peptide in the output is still paired with its respective prediction and the order has not shifted.

Thanks for you help!

```sh
python scripts/predict.py -m gru -w saves/kim2014/mhcnuggets_gru/H-2-KB.h5 -p test_in.txt > test_output.txt

Traceback (most recent call last):
  File "scripts/predict.py", line 96, in <module>
    main()
  File "scripts/predict.py", line 92, in main
    predict(opts['model'], opts['weights'], opts['peptides'])
  File "scripts/predict.py", line 57, in predict
    print(peptide, ic50s[i])
IndexError: list index out of range
```

**Comment by rbhatta8** [comment]
Hi there! Currently we only support peptides up to a maximum length of 11 (which is a reasonable assumption for MHC Class I). Peptides that are longer are dropped, but we probably should have handled that more gracefully, thanks for the catch!

**Comment by leeprichman** [comment]
Thanks for responding so quickly.  That makes sense, but the test output that i included does have peptides longer than 11 amino acids so it doesn't seem like they are immediately dropped.  Does this mean the peptides and affinities from this output are likely not properly paired?

**Comment by rbhatta8** [comment]
Yes that's correct, the outputs are not properly paired in this case (hence, the index out of bounds error). I'll be pushing out a fix to this soon, right after the production models are ready for release! :-)

**Comment by leeprichman** [comment]
Awesome, thanks so much for the help.
