### ISSUE TITLE
Do not use colon in file names

### ISSUE THREAD

**Issue by saskra** [KarchinLab/mhcnuggets#3]
While I mostly use Linux I sometimes have to do things on Windows where colons in filenames are not allowed. To this end, I had to rename all the files named according to alleles having a ":" in the name and replace all colons in the lists and the source code. It would be nice if future releases would account for that and avoid special characters besides underscores and/ or accept different naming conventions, e.g. via [mhcnames](https://github.com/openvax/mhcnames). :-)

**Comment by rbhatta8** [comment]
You make a good point @saskra , and initially we didn't have any special characters in our naming scheme so I'm on board with you there. We had a few other users who wanted the ":" to be included for biological clarity reasons. Thanks for sharing the link, maybe that provides a happy medium for naming schemes a biologist might want and what a computer is happy with as well. We'll try to include a fix in our next update!
