### ISSUE TITLE
Use all alleles and peptides at once

### ISSUE THREAD

**Issue by saskra** [KarchinLab/mhcnuggets#4]
Is there a way to train on all supported alleles and a "complete" list of peptides at once, or do I have to train 371 single-allele-predictors? And is there a pretrained model giving me the binding predictions for a list of peptides with all alleles?

**Comment by richelbilderbeek** [comment]
Hi @saskra,

Regarding training: I do not know.

Regarding using pre-trained data: there are some pre-trained models. You can supply to (max 15-mer) peptides to a file and run MHCnuggets on it. If you enjoy R, you may enjoy [mhcnuggetsr](https://github.com/richelbilderbeek/mhcnuggetsr), which does allow you to predict IC50s in multiple ways. Disclaimer: I am the author of that R package.

**Comment by XiaoshanShao** [comment]
@saskra Yes if you want to train the alleles differently from what we did, you will have to train them one-by-one. The pretrained models are all in the saves folder of the source code, you can just the "predict" function to get any IC50 for your list of peptides, but that has to be done to one allele at a time as well.
