### ISSUE TITLE
How to use training data without IC50(nM)

### ISSUE THREAD

**Issue by lujianliang** [KarchinLab/mhcnuggets#5]
Hi, I have some mass spectrum data, which is labeled but without affinity value, 
for example:
mhc,peptide,IC50(nM)
HLA-A0201,ILLSGIYNV,1.0
HLA-A0201,NLLPIMFEV,1.0
HLA-A0201,GMLDGLVNV,1.0

error report while I'm training use MHCnuggets.
part of information is as below:
return 1-math.log(ic50, MAX_IC50)
ValueError: math domain error

I guess is because IC50(nM) value, 
Is there any way to use MHCnuggets training my data?

thanks

**Comment by rbhatta8** [comment]
I would recommend converting the mass spec values to something that resembles IC50 values. If all the values are either 0/1 for your case, you might want to consider the 1s to ~100 nM and the 0s to ~20,000 nM

**Comment by lujianliang** [comment]
Thank you very much.
I will try this way.
Another way, I want to predict all my training data with netMHCpan4.0, I can get  IC50 values, using those IC50 values, I can train MHCnuggets model, and then predict test data. The problem is the IC50 values predict by netMHCpan4.0 may be deviation or even completely wrong, and may mislead the training model of MHCnuggets. 
How do you think about this approach?
thanks

**Comment by rbhatta8** [comment]
As you pointed out yourself, that is probably not a very good approach to training a model.
