### ISSUE TITLE
library version requirements

### ISSUE THREAD

**Issue by jmerkin** [KarchinLab/mhcnuggets#5]
There are some incompatibilities with recent versions of tensorflow and keras. Installing tensorflow==1.4.1 (or probably 1.X) and keras 2.1.2 (probably 2.1.X) solves it.

**Comment by richelbilderbeek** [comment]
Is the current situation OK now?

**Comment by jmerkin** [comment]
I can't check. I no longer work at that company. I think it should be pretty straightforward to test with a virtual environment though.

**Comment by richelbilderbeek** [comment]
I am not a Python user, maybe @XiaoshanShao know the answer to this :+1:
